using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum VFXType
{
    HIT_NORMAL,
    HIT_CRITICAL,
    DASH_TRAIL_BLUE,
    DASH_TRAIL_RED,
    DASH_TRAIL_GREEN,
    DASH_TRAIL_PURPLE,
    MAGNET_ACTION_EXPLOSION,
    SKILL_KATANA,
    MAGNETIC_SWITCH_N,
    MAGNETIC_SWITCH_S,
    DODGE_DUST,
    JUMP_DUST,
    BOMB_EXPLODE,
    ENEMY_MUZZLE_BURST,
    WHIRLWIND_KATANA,
    MAGNETIC_SHIELD_N,
    MAGNETIC_SHIELD_S,
    MAGNETIC_PULLING,
    PARRY,
    CHARGING_ARCHER_SKILL,
    MAGNET_AIM_SHOCKWAVE,
}

public enum DAMAGEType
{
    NORMAL,
    CRITICAL,
    POISON,
    MAGNETIC,
    UI_DAMAGE,
    FIRE,
    BLEED,
}